### PR TITLE
Karma Saucelabs Integration [fix #163]

### LINKED ISSUE #163: karma saucelabs
run karma build against multiple browsers on saucelabs.

https://saucelabs.com/opensauce

### PR DESCRIPTION
**Pull request by svnlto**
This PR essentionally fixes resolves 2 issue.
1. we can now run Karma with different sets of configuration, i.e `karma:dev`, `karma:coverage` etc.
2. when ran on travis karma will head over to saucelabs and run its tests on a set of browsers and return the results back to travis achieving running tests on multiple plattforms.

### CODE REVIEW

**Comment by gr2m** [comment]
hey sven, what's the `build` branch for?

**Comment by svnlto** [comment]
it's a feature branch... I didn't want to start this big chunk of work on dev, so I branched off of dev instead.

**Comment by gr2m** [comment]
Ay gotcha! Looks good to me! Or anything particular I should look into? I've just seen that you downgraded karma, why's that?

**Comment by svnlto** [comment]
@janl @gr2m can you add a set of browsers we want to run this against.

**Comment by svnlto** [comment]
>  I've just seen that you downgraded karma, why's that?

Some peer dependency issue...

**Comment by gr2m** [comment]
Where to add the browsers?

I'd add latest Chrome, Firefox, Safari + future versions
And ie10+

**Comment by gr2m** [comment]
@svnlto can you add 
- latest Chrome+
- latest Firefox+
- latest Safari+
- IE10+

as browsers to test with saucelabs? I guess you add it to Gruntfile.js, right? But I don't know the syntax. If you could do it or point me to the right docs, that'd be great

**Comment by svnlto** [comment]
@gr2m the syntax is pretty straightforward... https://github.com/hoodiehq/hoodie.js/blob/7ef867e81e9561141b4e4312bbe6e256d066a743/Gruntfile.js#L100

**Comment by gr2m** [comment]
I get an error when running `grunt karma:dev`

```
$ grunt karma:dev
Running "karma:dev" (karma) task
INFO [karma]: Karma v0.10.5 server started at http://localhost:9876/
INFO [launcher]: Starting browser PhantomJS
WARN [watcher]: Pattern "/Users/gregor/JavaScripts/hood.ie/hoodie.js/lib/jquery/jquery.js" does not match any file.
WARN [watcher]: Pattern "/Users/gregor/JavaScripts/hood.ie/hoodie.js/lib/expect/expect.js" does not match any file.
WARN [watcher]: Pattern "/Users/gregor/JavaScripts/hood.ie/hoodie.js/lib/sinonjs/sinon.js" does not match any file.
INFO [PhantomJS 1.9.2 (Mac OS X)]: Connected on socket LU8v2XKd3OOmogyXJQJJ
PhantomJS 1.9.2 (Mac OS X) ERROR
    ReferenceError: Can't find variable: $
    at /Users/gregor/JavaScripts/hood.ie/hoodie.js/test/lib/helpers.js:5
PhantomJS 1.9.2 (Mac OS X): Executed 0 of 0 ERROR (0.08 secs / 0 secs)
Warning: Task "karma:dev" failed. Use --force to continue.

Aborted due to warnings.
```

the `lib` folder is in `.gitignore`, dunno why

I'd like to limit the root folders of the repository to a minimum. Why not move the libraries into /test/lib and move /coverage & /support below /test as well?

**Comment by svnlto** [comment]
> the lib folder is in .gitignore, dunno why

to avoid being checked in, run `bower install`

**Comment by gr2m** [comment]
gotcha.

I get a sauce labs error now:

```
$ grunt karma:continuous
Running "karma:continuous" (karma) task
INFO [karma]: Karma v0.10.5 server started at http://localhost:9876/
INFO [launcher]: Starting browser PhantomJS
INFO [launcher]: Starting browser chrome (mac 10.8) on SauceLabs
INFO [launcher]: Starting browser safari (mac 10.8) on SauceLabs
INFO [PhantomJS 1.9.2 (Mac OS X)]: Connected on socket WwoaIGicF8S15bQaMwjF
ERROR [launcher.sauce]: Can not start safari (mac 10.8) on SauceLabs
  The environment you requested was unavailable.
  Tunnel identifier provided: 'karma1385381956', didn't match any running tunnel for your account Please remove or specify a different tunnel-identifier. For more info, please check http://saucelabs.com/docs/connect#tunnel-identifier
ERROR [launcher.sauce]: Can not start chrome (mac 10.8) on SauceLabs
  The environment you requested was unavailable.
  Tunnel identifier provided: 'karma1385381956', didn't match any running tunnel for your account Please remove or specify a different tunnel-identifier. For more info, please check http://saucelabs.com/docs/connect#tunnel-identifier
Warning: Task "karma:continuous" failed. Use --force to continue.

Aborted due to warnings.
```

Couldn't figure out the problem. To have to change some settings in your account to allow me to run it as well? Sorry, never used sauceLabs before

**Comment by gr2m** [comment]
ok nevermind, works now, I think updating Java fixed it :)

**Pull request merged**
