### PR TITLE
Use `hapi-cors-headers` to correctly respond to OPTIONS requests

### PR DESCRIPTION
**Pull request by jameswestnz**
@gr2m

Related to Issue #493

### CODE REVIEW

**Comment by gr2m** [comment]
@jameswestnz thanks, LGTM!

Ping @hoodiehq/maintainers

**Comment by HipsterBrown** [comment]
:clap: Wonderful addition @jameswestnz!

LGTM!

**Comment by jameswestnz** [comment]
Was only luck I found your hapi plugin, @gr2m - I started writing something similar, then thought I'd see if anyone else had solved for hapi.... funnily enough I find your hapi plugin! So I call this PR my luck, and your hard work ;)

**Comment by rogeriochaves** [comment]
LGTM 👍

**Comment by gr2m** [comment]
Thanks y’all! Released as [v22.2.1](https://github.com/hoodiehq/hoodie/releases/tag/v22.2.1)

@rogeriochaves Thanks a lot for the review 👍 💯  If you like to help with reviews in future, I’d love to add you to the Maintainers team. Your help would be much appreciated :) We usually ping `@hoodiehq/maintainers` on PRs that need a second review, so you will get a few notifications

**Comment by rogeriochaves** [comment]
@gr2m okay, I'll try to help!

**Comment by gr2m** [comment]
Welcome to the team, @rogeriochaves :)

**Pull request merged**
