### PR TITLE
bug fix for store.on signatures and addition of findAll

### PR DESCRIPTION
**Pull request by bbn**
<3

### CODE REVIEW

**Comment by gr2m** [comment]
Thanks :)

**Comment by bbn** [comment]
A pleasure! Question: what is the best way to make use of this backbone-hoodie lib in a hoodie project? Currently I'm just copying the file into my vendor directory.

**Comment by gr2m** [comment]
spontaneously, I'd make an own repo for it, what you think? Wanna start one?

It could have backbone-hoodie.js. We can add the .coffee version. Add a nice readme with some examples?

**Comment by bbn** [comment]
ok cool. I'll do it later today. we remove it from this repo then?

**Comment by gr2m** [comment]
awesome! And yes, I'll remove it then

**Comment by bbn** [comment]
okay, i've got something basic going:
https://github.com/bbn/backbone-hoodie

fixed a few more bugs as well!

**Comment by gr2m** [comment]
this is so cool! I'll soon get back to my own project, which is also based on Backbone, looking forward to use your adapter!

**Pull request merged**
