### PR TITLE
Added a line on how to stop server.

### PR DESCRIPTION
**Pull request by jsoranno**

### CODE REVIEW

**Comment by gr2m** [comment]
LGTM – let’s squash and merge with `feat: Added a line on how to stop server`

**Comment by gr2m** [comment]
Thanks @jsoranno, that was awesome 👏 Are you on twitter? We like giving new contributors a shout out :) I’ll also invite you to the Hoodie Contributors Team! Welcome 👋  you should see an invitation on https://github.com/hoodiehq

**Comment by jsoranno** [comment]
Yes! @juanitasoranno

Thanks so much for all your help tonight, Gregor. I'm so excited! I had so much fun learning soooo much so fast. 

-Juanita Soranno

On May 25, 2016, at 10:39 PM, Gregor Martynus notifications@github.com wrote:

Thanks @jsoranno, that was awesome 👏 Are you on twitter? We like giving new contributors a shout out :) I’ll also invite you to the Hoodie Contributors Team! Welcome 👋

**Comment by gr2m** [comment]
Thanks @jsoranno, shout out done! Let me know if you want to contribute something again :) Best to say hi in http://hood.ie/chat or just grab another issue from https://github.com/hoodiehq/camp/issues (nevermind the your first PR, you can have another one if it helps you to get going with the project :)

**Pull request merged**
