### PR TITLE
Run tests on save of spec file

### PR DESCRIPTION
**Pull request by garrensmith**
Update Gruntfile to watch for spec changes and then run tests

### CODE REVIEW

**Comment by gr2m** [comment]
ah, I think the line above (commented out) does the same thing, right?

```
//files: ['<%= jshint.files %>'],
```

I'm not sure why we removed it though ... maybe @svnlto knows?

**Comment by svnlto** [comment]
pretty much, yes.

**Comment by garrensmith** [comment]
Ok I've just pushed a change that uncomments that line and removes the current line.

**Comment by gr2m** [comment]
sweet, cheers!

**Pull request merged**
