### PR TITLE
[refact] new folder structure

### LINKED ISSUE #230: change /src folder structure
see https://gist.github.com/gr2m/809ae8f31923139e5a0a cc @svnlto

### PR DESCRIPTION
**Pull request by gr2m**
closes #230

### CODE REVIEW

**Comment by gr2m** [comment]
Once that's merged, I'll do some cleanup
- remove `hoodie.dispose()`
- remove `hoodie.genereateId()`, `hoodie.request()` and the promiseAPI. Use them internally only instaed

**Comment by svnlto** [comment]
so can you clarify ( maybe even document the new file layout ) in the README?

**Comment by gr2m** [comment]
like this?

https://github.com/hoodiehq/hoodie.js/blob/a3e82b6a964164eff5776ebe02bc1b02e72000f1/quickstart_for_developers.md#hoodie-folders--files

**Comment by gr2m** [comment]
merged via https://github.com/hoodiehq/hoodie.js/commit/cb0bfd360114a71903bf550276655b61dfe714af

**Pull request closed without merging**
