### PR TITLE
I think I may have gone at least some of the way to fixing #233

### PR DESCRIPTION
**Pull request by lewiscowper**
I'm new to the web/JS development world, and I took this on to try and look through a large codebase, I was just wondering whether this is what you were looking for with issue #233, and whether anyone could look through this and see if I've missed anything.

### CODE REVIEW

**Comment by svnlto** [comment]
LGTM

**Comment by gr2m** [comment]
Thanks Lewis! Merged via https://github.com/hoodiehq/hoodie.js/commit/b74e37e4c9b4fc0807fd27f2c1c0699758c22726

Great job, much appreciated! We're super proud that to your first bigger web/JS project you contributed to, may there come many more :)

**Comment by dch** [comment]
way to go @tenmilestereo \o/ welcome!

**Pull request closed without merging**
