### PR TITLE
Dont need to accept.

### PR DESCRIPTION
**Pull request by hamzahsarwari**
DEMO

### CODE REVIEW

**Comment by gr2m** [comment]
Hey Hamzah, if you just want to test pull requests, the best way to do that is to create a repository on your own account and play around with it.

**Comment by gr2m** [comment]
Please stop doing this
screen shot 2016-10-01 at 10 04 28

It’s taking time of maintainers of these projects, and it’s unfair towards the other participants of Hacktoberfest who actually put in an effort to get the T-Shirt. I’m very disappointed :(

**Comment by hamzahsarwari** [comment]
I am sorry, i was unaware of what damage i was doing.

**Comment by gr2m** [comment]
@hamzahsarwari it would be really nice if you would go and send 4 more pull requests that are helpful? That would make up for it :) Happy to help you find something here on Hoodie, but there are many other projects, too

**Comment by hamzahsarwari** [comment]
Yes please! i have little to no coding experience, but if there is something i can do i would be more than happy to :)

**Comment by gr2m** [comment]
Okay I’ll look trough issues today, if I’ll let you know if I find a good beginner-friendly issue. For the time being, I can recommend the JavaScript track at http://exercism.io/, and here’s a good tutorial on how to send Pull Requests on GitHub: https://egghead.io/courses/how-to-contribute-to-an-open-source-project-on-github

**Comment by hamzahsarwari** [comment]
I have finished the lessons and went through the exercism site, is there anything i can help with now? :)

**Pull request closed without merging**
