### PR TITLE
hoodie.js v0.5

### PR DESCRIPTION
**Pull request by gr2m**
I'd like to merge the work on browserify (and all the other fixes in `dev` branch) as soon as possible. 

I'd see it as a step towards v0.6-wasabi wich will be mainly internal refactoring / structuring / proper use of browserify etc.

### CODE REVIEW

**Comment by svnlto** [comment]
still breaks?

**Comment by gr2m** [comment]
again, sorry, on it, give me 15min

**Comment by gr2m** [comment]
specs are green again

**Comment by gr2m** [comment]
please wait with merging, I run into a problem with the build.

Also, on question: can plugin developers now somehow access our internal modules, like `hoodie/store` etc, so they can build upon it? If so, how? The `require` is been made available to outside hoodie, right?

**Comment by gr2m** [comment]
build is good again. 

@svnlto What you think about exposing internal hoodie.js modules for plugin developers?

**Comment by svnlto** [comment]
wouldn't want to do this just yet.

**Comment by gr2m** [comment]
okay cool. Good to merge from my side then

**Pull request merged**
