### PR TITLE
Rename bearer in the Authorization header to session.

### LINKED ISSUE #485: rename "bearer" to "session" in Authorization header
rename bearer in our Authorization header to session, because that’s what it is, and we don’t use bearer tokens anywhere else in our code. It’s unnecessary confusing. So instead of Authorization: bearer sessionid123 header, we would have Authorization: session sessionid123

### PR DESCRIPTION
**Pull request by ddmck**
closes https://github.com/hoodiehq/hoodie/issues/485

### CODE REVIEW

**Comment by HipsterBrown** [comment]
LGTM :+1:

Thanks for working on this @ddmck!

**Comment by gr2m** [comment]
Perfect thanks @ddmck, LGTM.

Are you on twitter? We like giving shout outs to new contributors :) I also invited you to the Hoodie Contributors team, you can now create branches on our repos directly instead of forking :) And you can assign yourself to issues. Welcome!

**Comment by gr2m** [comment]
We have to update `hoodie-client`, `hoodie-account-client` and `hoodie-account-server` at the same time, I’ll leave this open for now. If you like check the other repos for the change, too

**Comment by gr2m** [comment]
Okay I prepared pull requests for account client & server:
- [x] https://github.com/hoodiehq/hoodie-account-client/issues/100
- [x] https://github.com/hoodiehq/hoodie-account-server/issues/161

Once merged an new breaking versions released, we have to start a PR for https://github.com/hoodiehq/hoodie-account to update dependencies (and close the PRs by Greenkeeper) and release it as well as a breaking change.

Once that is released, we can merge this PR, also as a breaking change, as the account JSON API changed.

ping @hoodiehq/maintainers 👀

**Comment by gr2m** [comment]
done via e63a0dd, 65c6a3f, f3dd07e

**Pull request closed without merging**
