### PR TITLE
100% test coverage

### LINKED ISSUE #4: 💯 Code Coverage for hoodie
This is a [starter issue](http://hood.ie/blog/starter-issues.html). It’s reserved for participants of [OSCON Contribute](https://ti.to/hoodie/oscon-meet-the-hoodies) until May 20th, 2016. 
### :octocat:  Your First Pull Request?

We would like to take the opportunity to invite someone who did not yet contribute to Hoodie to work on this issue. Follow [@YourFirstPR](https://twitter.com/yourfirstPR) on Twitter for more of these issues across many open source projects :)
### 🤔 What you will need to know

JavaScript, Node.js. Knowledge about [npm](https://docs.npmjs.com/) would be helpful but are not required, you’ll figure it out as you go :)
### :dart: The goal

100% code coverage makes sure that every single line of code is covered by tests. And it looks pretty cool once we have all the 💯 for all modules in [Hoodie’s Architecture](https://github.com/hoodiehq/hoodie/tree/master/server#architecture)

The current status is [Coverage Status](https://coveralls.io/r/hoodiehq/hoodie?branch=master)
screen shot 2016-10-01 at 12 30 49
### :clipboard: Step by Step
- [x] claim this issue: assign yourself if you are part of the Hoodie team, otherwise comment below :)
- [x] replace `up for grabs` label with `in progress`
- [x] [Setup the hoodie repository locally](https://github.com/hoodiehq/hoodie#testing) and make sure that all tests pass
- [x] Bring coverage to 100%. Use the following steps
  - run `npm test`
  - run `node_modules/.bin/nyc report --reporter=lcov`
  - open `coverage/lcov-report/index.html`. It will look something like this: coverage
- [x] If you are all 100%, commit with `test: 100% coverage`. If you have blockers commit with `test: coverage` and move on, we can discuss details in the pull request
- [x] Start a Pull Request. Mention `closes hoodiehq/camp#4` in the description.  
  If this is your first, welcome :tada: :smile: [Here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request
- [x] Done :+1: Replace the `in progress` label with `ready`. Ask in comments for a review :)

Ping us in the [Hoodie Chat](http://hood.ie/chat/) or on [Twitter](https://twitter.com/hoodiehq/) if you have any questions :)

### PR DESCRIPTION
**Pull request by oluoluoxenfree**
closes hoodiehq/camp#4

This is still a WIP.

### CODE REVIEW

**Comment by gr2m** [comment]
hey Olu, how are things going? Anything we can help with?

**Comment by gr2m** [comment]
Hey Olu, are you still working on this one?

**Comment by oluoluoxenfree** [comment]
Hi, sorry for the slow response, I've been very busy!

I can continue this weekend, but if it's too urgent feel free t hand it off.

**Comment by gr2m** [comment]
no urgent at all! In case you started working on it, make sure to pull the latest changes from the master `branch`. Let us know if you have any questions :)

**Comment by gr2m** [comment]
hey Olu, we have quite a big pull request coming up that will change a lot of the code. If you have more work that’s already done, can you push it and we incorporate it before the refactoring we are currently working on, and then resume the 100% test coverage issue after the refactoring?

**Comment by oluoluoxenfree** [comment]
Feel free to go ahead, I haven't got anything new

**Comment by gr2m** [comment]
Closing as we did a big cleanup of `hoodie` meanwhile, see https://github.com/hoodiehq/camp/issues/4#issuecomment-242254644

**Pull request closed without merging**
