### PR TITLE
docs: correct hoodie.account code examples

### LINKED ISSUE #122: fix code examples in hoodie.account API documentation
This is a [starter issue](http://hood.ie/blog/starter-issues.html). It’s up for everyone for taking :) New contributors welcome <3

### 🤔 What you will need to know

Our [documentation website](http://docs.hood.ie/en/latest/)’s source code is part of the [hoodie](https://github.com/hoodiehq/hoodie) repository and lives in the [`docs/`](https://github.com/hoodiehq/hoodie/tree/master/docs) folder. Each time there is an update to the repository’s `master` branch, the documentation on [docs.hood.ie](http://docs.hood.ie/en/latest/) gets rebuild automagically through https://readthedocs.org ✨ 

The Documentation is built from `*.rst` files, which stands for [reStructuredText](http://www.sphinx-doc.org/en/stable/rest.html). It’s mostly text and has some special syntax for things like tables or code highlights. Don’t worry if that’s new to you, you’ll get the hang of it 👍 

### 🐞 The Bug

Open the [hoodie.account](http://docs.hood.ie/en/latest/api/client/hoodie.account.html) documentation page. Most examples correctly show `hoodie.account`, but some towards the and only show `account`. For example, `account.profile.get(properties)` should be `hoodie.account.profile.get(properties)`.

### :clipboard: Step by Step
- [x] 🙋 **Claim this issue**: Comment below (or assign yourself and continue at step 4 :)  
  Please 🙏 only claim if you want to start working on it within a day.  
  Once claimed we add you as contributor to this repository.
- [x] 👌 **Accept our invitation** to this repository. Once accepted, assign yourself to this repository
- [x] 👓 **Please review** our [Code of Conduct](http://hood.ie/code-of-conduct/)  
  In a nutshell: be patient and actively kind with us 😊
- [x] 🔄 **replace** the `up for grabs` label with `in progress`.
- [x] You can make the edits directly in the browser if you like. Click the "Edit on GitHub" button on top right of the [`hoodie.account` documentation page](http://docs.hood.ie/en/latest/api/client/hoodie.account.html). Make the changes and commit them with `docs: correct hoodie.account code examples`
- [x] 🔀 **Start a Pull Request**. Mention `closes hoodiehq/camp#122` in the description.  
- [x] 🏁 **Done** :+1: Replace the `in progress` label with `ready`. Ask in comments for a review :)

### 🤔❓ Questions

Ping us in the [Hoodie Chat](http://hood.ie/chat/) or on [Twitter](https://twitter.com/hoodiehq/)

### PR DESCRIPTION
**Pull request by lucask42**
closes hoodiehq/camp#122, closes #788

### CODE REVIEW

**Comment by gr2m** [comment]
you missed just one I think :)

> `options` as they were passed into `account.signIn(options)`

**Comment by lucask42** [comment]
You're right, I fixed my error and pushed it to my fork.  Let me know if I need to make a new pull request, it kind of looks like the most recent change just became part of this pull request.

**Review by gr2m — APPROVED** [review]
perfect, thanks :)

**Comment by gr2m** [comment]
yes, you updated this pull request, which is exactly right 👍 thanks for your help @lucask42

**Comment by lucask42** [comment]
Thanks to you for creating the issue and helping me get through it.  Woo!

**Pull request merged**
