### PR TITLE
deployment.rst updated

### PR DESCRIPTION
**Pull request by sohini-roy**
Documentation has been completely updated

### CODE REVIEW

**Comment by gr2m** [comment]
Hey @sohini-roy, I’m not sure what you try to do here? It looks like you took content from other pages of the documentation and added them to the bottom of the documentation for deployment?

What is it you try to achieve? I’m sorry but I am a bit confused

**Comment by gr2m** [comment]
Ah I see the issue now that you are working on: https://github.com/hoodiehq/camp/issues/24

The issue is about adding instructions on how to deploy a Hoodie app to a linux server, you have to create that content first. Do you have experience in linux/deployments?

Here are some docs for the old Hoodie, for reference: https://github.com/hoodiehq/documentation/blob/gh-pages/en/deployment/linux.md

**Comment by sohini-roy** [comment]
Ok I was mistaken :( I wasn't clear about it. I have understood it and I a trying to deploy https://github.com/hoodiehq/hoodie-app-tracker on a Linux server to be properly acquainted with it.
After which I will write the documentation about it.

**Comment by gr2m** [comment]
Thanks a lot @sohini-roy :)

**Comment by varjmes** [comment]
Going to close this, and once you're all versed in Linux land, we can open a new PR :)

**Pull request closed without merging**
