### PR TITLE
dont-break hoodie-app-tracker

### PR DESCRIPTION
**Pull request by gr2m**
Instead of having own test, we want to use our [new starter application’s test suite](https://github.com/hoodiehq/hoodie-app-tracker/tree/master/test) using [dont-break](https://www.npmjs.com/package/dont-break).

Unfortunately things don’t work yet. @bahmutov could you maybe help us to get it working? That’d be super helpful :)

### CODE REVIEW

**Comment by gr2m** [comment]
Interestingly, this fails locally on my Mac, but it seems to work on Travis, all tests pass, but at the end there is some symlink issue: https://travis-ci.org/hoodiehq/hoodie/builds/125444809#L1135

But I can’t get it to work locally on my mac, here’s the log: https://gist.github.com/8d6c65172ad7462cceba47d0c4d07373

**Comment by janpawellek** [comment]
Hi @gr2m !
I encounter the same issue when running `npm test` with `node v5.9.1 (npm v3.8.6)`.
For me, it works when using `node v4.4.3 (npm v2.15.1)` though.
Since you are using node v4.2.2 and npm v3.8.6 and it fails, it might be an issue with the v3 npm?

**Comment by gr2m** [comment]
Thanks Jan for looking into it!

**Comment by gr2m** [comment]
This got closed due to merge of `hoodie-server` and `hoodie`. I’ll reopen it again later

**Pull request closed without merging**
