### PR TITLE
rename db to PouchDB in README

### PR DESCRIPTION
**Pull request by anu0012**
This PR is part of https://github.com/hoodiehq/hoodie/issues/555

### CODE REVIEW

**Review by gr2m — CHANGES_REQUESTED** [review]
Hey @anu0012, there is much more to this issue than just updating the pull request, we need to update the tests and implementation, too. For example see https://github.com/hoodiehq/hoodie/blob/master/server/index.js#L23, the code expects `options.db` right now, it all needs to be changed.

**Comment by gr2m** [comment]
Before sending a pull request, it’s better to ask in the issue first and suggest how you would resolve it, once agreed you can start working on it. That saves us all some time :)

**Comment by anu0012** [comment]
@gr2m I am sorry for that. So we want to change option.db in the whole code with Pouch.db. Am I right ?

**Comment by gr2m** [comment]
@anu0012 let me create a new issue with more background information and instructions, okay? We’ve invited you to the Camp repository, you can accept the invitation at https://github.com/hoodiehq/camp/invitations. Once accepted I can assign you to the issue (that I will create in a moment)

**Comment by anu0012** [comment]
@gr2m  Thanks for the invitation .

**Comment by LowProfileDog** [comment]
there you go: https://github.com/hoodiehq/camp/issues/51 hope the instructions help? You can continue working on this pull request, or close this one and start afresh, as you prefer

**Pull request closed without merging**
