### PR TITLE
Promises

### PR DESCRIPTION
**Pull request by eth0lo**
This substitutes jQuery.Defer with a bluebird implementation. This will allow to coexist the deferred syntax with the Promises constructor, thus allowing to change the rest of hoodie to the new syntax one piece at a time.

### CODE REVIEW

**Comment by gr2m** [comment]
woah, thanks Jean! Could you please rebase your commits on master? Then I'd like to have @svnlto a look as he started to work on replacing jQuery in the promise branch:
https://github.com/hoodiehq/hoodie.js/tree/promise

**Comment by eth0lo** [comment]
I was in IRC talking with him and this PR is against his branch

**Comment by svnlto** [comment]
awesome! can you fix the tests on this PR too?

**Comment by eth0lo** [comment]
My tests are green, the issue is that the pull request is against the promises branch, and not master, thus making the tests fail, I could do it against master if you agree

**Comment by svnlto** [comment]
I think rebasing from master and would be a good idea.

**Pull request merged**
