### PR TITLE
feat: updated developer documents and lint tests

### PR DESCRIPTION
**Pull request by fozy81**

### CODE REVIEW

**Comment by gr2m** [comment]
@fozy81 could you please go trough the other repositories listed in http://docs.hood.ie/en/latest/about/architecture.html and see if we link to the `CONTRIBUTING.md` file that you moved in this PR? Just to make sure we don’t have any dead links

**Comment by fozy81** [comment]
Thanks, I've updated that. Made a couple of other minor changes while I was at it.

**Comment by gr2m** [comment]
looks good 👍 

What I meant is that we have other repositories that deep link the current `CONTRIBUTING.md`, see https://github.com/hoodiehq/hoodie-client#contributing for example

We should have PRs ready to fix that once we merge this PR

**Comment by fozy81** [comment]
Ah yes, I'll take a look through the other repos. :eyeglasses:  And ready some PRs.

**Comment by gr2m** [comment]
@fozy81 I went ahead and merged the PR as @NimmiW wants to help with the documentation and I wanted her to do so upon all the great work you did here :) 

@NimmiW meet @fozy81 who has the best insights about how documentation is setup at Hoodie right now :)

**Review by gr2m — APPROVED** [review]

**Comment by gr2m** [comment]
@fozy81 hmmm can you confirm if your changes actually appear on http://docs.hood.ie/en/latest/?

**Comment by fozy81** [comment]
@gr2m That's strange, docs not appearing on http://docs.hood.ie/en/latest/. The list of builds shows there was an error, http://readthedocs.org/projects/hoodie/builds/5075127/

I'll looking into the error, but not making much sense to me at the moment

**Comment by gr2m** [comment]
@fozy81 there is a slack community on http://www.writethedocs.org/, maybe worth joining their slack and ask for help? I’m quite sure they have people experience with it :)

Thanks SO MUCH for all your help :)

**Comment by fozy81** [comment]
Okay, I've left a message on writethedocs slack and issue on readthedocs github https://github.com/rtfd/readthedocs.org/issues/2669

Will wait until docs are built correctly before correcting links to contirbuting guidance in the other repos.

Thanks for your help/reviewing.

**Comment by fozy81** [comment]
@gr2m Could you check the setup on the read the docs dashboard. There should be a 'Python configuration File' path set. Could you check where that is pointing? should be docs/config.py

I just wonder if the config.py has changed somehow between pull requests etc?

**Comment by gr2m** [comment]
I’ve set the path now

image

**Comment by fozy81** [comment]
My current feeling is that the [conf.py file](https://github.com/hoodiehq/hoodie/commit/00a8e28291f1bb8e2047eadaba70e5fc889aa7ab#diff-85987f48f1258d9ee486e3191495582d)  is the issue, perhaps  line 78-90. Everything built locally okay, But I'll revert back and add things incrementally. I've setup a personal account on readthedocs whichI'll hook my clone on github to that. This should be easier to debug now. Just won't get a chance until tomorrow.

**Comment by fozy81** [comment]
@gr2m - The issue is the conf.py file. Removing that makes rtd work.

**Pull request merged**
