### PR TITLE
anonymous signup: triggers 'account:signin', should trigger 'account:signin:anonymous'

### PR DESCRIPTION
**Pull request by gr2m**
I'm on it

### CODE REVIEW

**Comment by gr2m** [comment]
@svnlto for hot fixes we send pull requests directly against master, then rebase dev on it, right?

**Comment by gr2m** [comment]
I'll fix another related bug on the same branch for the sake of simplicity:
hoodie does not connect to remote on `account:signin:anonymous` event

**Comment by svnlto** [comment]
@gr2m please reopen PR against `dev`

**Comment by svnlto** [comment]
is this a hotfix?

**Comment by gr2m** [comment]
> is this a hotfix?

yes, it's a bug. When you subscribe to `account:signin` event, your callback gets called when you create a task from an anonymous account. It should not do that. And the last commit is to make sure that hoodie still connects to remote in case of an anonymous signup

**Pull request merged**
