### PR TITLE
Upgrade to good@7

### PR DESCRIPTION
**Pull request by gr2m**
The upgrade to good 7 needs changes to the way we use `good`, see changelogs: https://github.com/hapijs/good/issues/467

I looked into it but couldn’t figure it out myself, would be nice if someone with more experience good have a glance at it. We only use it in one file: [plugins/logger.js](https://github.com/hoodiehq/hoodie/blob/master/server/plugins/logger.js)

### CODE REVIEW

**Comment by AdriVanHoudt** [comment]
for reference: https://github.com/hapijs/good/issues/467

**Comment by gr2m** [comment]
@christophwitzko can you maybe have a look at this? I tried to migrate it but too much stuff changed and we seemed to have used some internal APIs and I have no idea how to migrate it :/

**Comment by gr2m** [comment]
see https://github.com/hapijs/good/issues/500#issuecomment-226604443

**Comment by gr2m** [comment]
closing in favor of https://github.com/hoodiehq/camp/issues/35

**Pull request closed without merging**
