### PR TITLE
On sign out right after push, the pushed objects don't trigger change events when signed in again

### PR DESCRIPTION
**Pull request by gr2m**
to reproduce

``` js
// end session (forces unauthenticated state)
$.ajax({type: 'DELETE', url:'/_api/_session'})

// add new object
hoodie.store.add('test', {})

// reauthenticate then sign out. account.signOut pushes local changes before ending session
hoodie.account.signIn(username, password, {silent: true}).done( hoodie.account.signOut )

// sign back in
hoodie.account.signIn(username, password)

// the "test" object is in the /_changes response, but not in local Storage
hoodie.store.findAll('test').done( function(objects) { alert(objects.length)})
```

### CODE REVIEW

**Comment by gr2m** [comment]
@boennemann @svnlto you mind if I merge this in without tests? I fixes the problem, that I've tested in my app. And the tests would become obsolete once we migrate to PouchDB. For such a minor tweak, I could live with it.

**Comment by svnlto** [comment]
@gr2m makes sense.

**Comment by boennemann** [comment]
`grunt release` won't work with a breaking build. So if you decide to proceed make travis pass somehow (:

**Comment by gr2m** [comment]
ARGS DIEEEEE KARMA DIEEEEEE
https://travis-ci.org/hoodiehq/hoodie.js/builds/30053657#L2142

@svnlto @boennemann do you know how to fix this? This drives me nuts

**Comment by boennemann** [comment]
```
grunt-browserify@1.2.12 wants browserify@>=2.35 < 3.0.0
karma-browserify@0.2.1 wants browserify@>=3.30.5
```

In other words you should at least update `grunt-browserify` so that it depends on browserify >= 3.30.5. Browserify should be updated as well. As far as I remember @svnlto mentioned that the config with the new grunt-plugin slightly changed.

**Comment by gr2m** [comment]
I tried but can't get this fixed. When I upgrade browserify, tests don't run anymore. If you see a way to get this fixed temporarely (until the refactoring is done), please do it. If not, I'll remove tests so I can release this, as it is fixing a critical problem. Or feel free to make a better suggestion

**Comment by boennemann** [comment]
As far as I understood @svnlto it's fixed on promise-restored already.

**Comment by svnlto** [comment]
@boennemann @gr2m yeah, this has been taken care of in the above mentioned branch. Still needs discussing when and what to merge tho.

**Comment by gr2m** [comment]
@boennemann @svnlto I'll merge after `promise_restored` gets merged.

**Pull request closed without merging**
