### PR TITLE
Commit conventions

### PR DESCRIPTION
**Pull request by gr2m**
I keep answering about our commit conventions, so I thought I’d put a summary
into our CONTRIBUTING.md

### CODE REVIEW

**Comment by boennemann** [comment]
I'd add a link to the full conventions, but this is a very good summary.

**Comment by gr2m** [comment]
updated, also added title for direct links:
https://github.com/hoodiehq/hoodie/blob/contributing-commit-message-conventions/CONTRIBUTING.md#commit-message-conventions

**Comment by boennemann** [comment]
LGTM

(note: when amending the sponsor message get's appended multiple times. I fixed that in this version of the githook: https://github.com/hoodiehq/grunt-release-hoodie/commit/7a7aaaf697780fdc30b5d1d47a0f5cb5c0cda799)

**Comment by gr2m** [comment]
I fixed the commit

**Comment by gr2m** [comment]
So if I write LGTM, does that count, too?

**Pull request merged**
