### PR TITLE
docs(contributing): add clear process of merging

### PR DESCRIPTION
**Pull request by varjmes**
:sparkles:

### CODE REVIEW

**Comment by schisepo** [comment]
Looks good to me.

**Comment by gr2m** [comment]
Maybe someone has an idea to explain it simpler / better, but this is better than what we have right now :)

LGTM

**Comment by Guria** [comment]
Typo: brnach

**Comment by boennemann** [comment]
Maybe we can add something about https://github.com/github/hub, which makes it really easy to check out forks locally. e.g.:

```
hub checkout https://github.com/hoodiehq/hoodie/pull/451
```

I think that's quite relevant for merging contributions from people who aren't collaborators (yet).

**Comment by varjmes** [comment]
> Maybe we can add something about https://github.com/github/hub, which makes it really easy to check out forks locally. e.g.:
> 
> hub checkout https://github.com/hoodiehq/hoodie/pull/451
> I think that's quite relevant for merging contributions from people who aren't collaborators (yet).

OMG I didn't know you could do this. And I have hub. This is going to make my life so much happier.

Will add that and update typos

**Comment by varjmes** [comment]
Updated :)

**Comment by boennemann** [comment]
LGTM

**Comment by gr2m** [comment]
very nice :+1:

**Comment by boennemann** [comment]
Thanks!

**Pull request merged**
