### PR TITLE
allow using '-' in obj id (eq: for UUID ' f5ba9fca-794e-11e4-b939-40fe3c...

### PR DESCRIPTION
**Pull request by jekill**

### CODE REVIEW

**Comment by janl** [comment]
Heya, the diff shows a lot more changes than are mentioned in the commit message, is that intentional? :)

**Comment by jekill** [comment]
@janl sorry, this change touches only one string in the file _src/hoodie/store/helpers.js_

```
-exports.SEMANTIC_ID_PATTERN = new RegExp(/^[a-z$][a-z0-9-]+\/[a-z0-9]+$/);
+exports.SEMANTIC_ID_PATTERN = new RegExp(/^[a-z$][a-z0-9-]+\/[a-z0-9-]+$/);  
```

The two other files were autogenerated.
Can I make another PR without autogenerated files?

**Comment by janl** [comment]
yes please :)

Best

## Jan

**Comment by jekill** [comment]
done :)

**Pull request closed without merging**
