### PR TITLE
fix: support npm5’s --save default for postinstall script

### PR DESCRIPTION
**Pull request by janl**
We now check PWD for `node_modules`, i.e.: we are only
in `node_modules` if we are doing `npm install hoodie`
somewhere, but not when running `npm install` in the
hoodie source directory.

Closes https://github.com/hoodiehq/hoodie/issues/746

### CODE REVIEW

**Comment by janl** [comment]
Ping @hoodiehq/maintainers <3

**Comment by gr2m** [comment]
I can’t get hoodie to install with npm5, it fails with an `Cannot read property 'find' of undefined` error. I think the problem is https://github.com/isaacs/node-glob/issues/341

```bash
$ node -v && npm -v && npm i hoodie
v8.0.0
5.0.2
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm ERR! Cannot read property 'find' of undefined
npm ERR! Cannot read property 'find' of undefined
```

Does it work for you?

**Comment by janl** [comment]
Works fine with:

```
v6.9.1
5.0.2
```

**Comment by gr2m** [comment]
I get the same error

```
$ npm init -y
Wrote to /private/tmp/hoodie-issues-760/package.json:

{
  "name": "hoodie-issues-760",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC"
}


$ npm i hoodie
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm ERR! Cannot read property 'find' of undefined
npm ERR! Cannot read property 'find' of undefined

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/gregor/.npm/_logs/2017-06-03T17_52_05_262Z-debug.log
$ node -v
v6.9.5
$ npm -v
5.0.2
```

This is very weird...

**Comment by gr2m** [comment]
okay my problem was unrelated and could be fixed via https://github.com/npm/npm/issues/16677#issuecomment-305357667.

Checking the PR now

**Review by gr2m — APPROVED** [review]

**Pull request merged**
