### PR TITLE
[Potentially Breaking] updated hoodie-server to version 9.0.1

### PR DESCRIPTION
**Pull request by hoodiebot**
Dear Hoodie maintainer,

[hoodie-server](https://github.com/hoodiehq/hoodie-server) just released a new major version -- [9.0.1](https://github.com/hoodiehq/hoodie-server/releases/tag/v9.0.1).
I'm just a bot and unfortunately I can't yet know if that breaks Hoodie as well.

Generally if a breaking change appears in a component there are two options:

1. A new version of an accompanying component makes up for the breaking change, so that if they're used together the public API doesn't break.
2. This is an actual breaking change for Hoodie as well.

Please try and figure that out with your amazing human brain.

In case of the former please wait for the accompanying component to release its new version and manually update both versions in one commit. You can close this PR.

In case of the latter please document the breaking change by adding another empty commit that declares the breaking change and includes migration instructions.

This could look something like this:

```
git commit --allow-empty
```

The editor opens.

> docs(changelog): declare breaking change
>
> BREAKING CHANGE: Feature xyz broke in version x.y.z of hoodie-whatever.
>
> Please use hoodie.foo() instead of hoodie.bar() from now on.

Thank you,

– HoodieBot :heart:

### CODE REVIEW

**Comment by gr2m** [comment]
> hoodie-server just released a new major version -- 9.0.1.

@boennemann that reads wrong to me. Shouldn't it say "just released a new patch version"?

**Comment by boennemann** [comment]
@gr2m Yes you're right, that's because we changed the algorithm that determines whether it's a push or PR https://github.com/hoodiehq/bundle-bump-bot/commit/2ffe5b62374bf2645d10cc9c5364ab35afcb0181

Need to fix the template based on that.

**Comment by Charlotteis** [comment]
Thank you hoodie-bot but you have recently opened a newer PR for a major version! Thus I must deny your contribution.

**Comment by Charlotteis** [comment]
@gr2m @boennemann added an issue for this with explanation on how it could be done https://github.com/hoodiehq/bundle-bump-bot/issues/5

**Pull request closed without merging**
