### PR TITLE
code coverage 100% fixes hoodiehq/camp#107

### LINKED ISSUE #107: 💯 Code Coverage for hoodie
### 🤔 What you will need to know

JavaScript, Node.js. Knowledge about [npm](https://docs.npmjs.com/) would be helpful but are not required, you’ll figure it out as you go :)
### :dart: The goal

100% code coverage makes sure that every single line of code is covered by tests. And it looks pretty cool once we have all the 💯 for all modules in [Hoodie’s Architecture](https://github.com/hoodiehq/hoodie/tree/master/server#architecture)

The current status is [Coverage Status](https://coveralls.io/r/hoodiehq/hoodie?branch=master)

image

### :clipboard: Step by Step

- [x] claim this issue: @sohini-roy
- [x] replace `up for grabs` label with `in progress`
- [x] [Setup the hoodie repository locally](https://github.com/hoodiehq/hoodie#testing) and make sure that all tests pass
- [x] Bring coverage to 100%. Use the following steps
  - run `npm test`
  - run `node_modules/.bin/nyc report --reporter=lcov`
  - open `coverage/lcov-report/index.html`. It will look something like this: coverage
- [x] If you are all 100%, commit with `test: 100% coverage`. If you have blockers commit with `test: coverage` and move on, we can discuss details in the pull request
- [x] Start a Pull Request. Mention `closes hoodiehq/camp#107` in the description.  
  If this is your first, welcome :tada: :smile: [Here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request
- [x] Done :+1: Replace the `in progress` label with `ready`. Ask in comments for a review :)

Ping us in the [Hoodie Chat](http://hood.ie/chat/) or on [Twitter](https://twitter.com/hoodiehq/) if you have any questions :)

### PR DESCRIPTION
**Pull request by Alice-anjali**
closes hoodiehq/camp#107

### CODE REVIEW

**Review by gr2m — APPROVED** [review]
👏 great work, thanks Alice!

**Comment by Alice-anjali** [comment]
Thank You! ^_^

**Comment by gr2m** [comment]
Alice, are you on twitter? We like giving shout outs to new contributors :) Also @sohini-roy, would love to give you a shout out, too :)

**Comment by Alice-anjali** [comment]
Yes I am on twitter. This is my twitter handle @AliceAnjali. We would love to continue working with you. ^_^

**Comment by sohini-roy** [comment]
Thank you. :-)  We would look forward to some new opportunities. This is my twitter handle @sohini_roy1996.

**Comment by gr2m** [comment]
I have it on the list and hope to find something new for you two to work on :) Thanks for your great contributions so far

**Comment by Alice-anjali** [comment]
:-)

**Pull request merged**
