### PR TITLE
fix(test/typo): change 'walktrough' to 'walkthrough'

### PR DESCRIPTION
**Pull request by varjmes**
Found a lil typo! :sparkles:

### CODE REVIEW

**Comment by gr2m** [comment]
In that case, we need to rename the filename, otherwise it would trough an error like "File not found". Odd that the tests pass, but the `master` branch is outdated, so maybe the tests are not really running anymore :)

**Comment by varjmes** [comment]
I did change the file name...

It says 2 files changed: `tests/unit/walktrough.js → tests/unit/walkthrough.js` "File renamed without changes"

:)

**Comment by boennemann** [comment]
LGTM

**Comment by NickColley** [comment]
LGTM :+1:

**Pull request merged**
