### PR TITLE
style(server): require full lodash

### PR DESCRIPTION
**Pull request by rmehner**
This is in accordance to `CODING_STYLE.md`.

See https://github.com/hoodiehq/hoodie/pull/559#discussion_r76828935

### CODE REVIEW

**Comment by gr2m** [comment]
That’s fine I think, we do it all over the server code. The thing we try to do is requiring the entire `lodash` package on server, while requiring the separated packages for the client

**Comment by rmehner** [comment]
> That’s fine I think, we do it all over the server code. The thing we try to do is requiring the entire lodash package on server, while requiring the separated packages for the client

Yep, that's what it says in the CODING_STYLE.md. I mean, `require('lodash').deepClone` requires the full lodash, but I guess that's something beginners might stumble over, so the way in the PR might be clearer and more approachable :)

**Comment by gr2m** [comment]
yeah you are right, I don’t mind merging, LGTM :)

**Comment by varjmes** [comment]
LGTM!

**Pull request merged**
