### PR TITLE
[minor] upgraded karma packages

### LINKED ISSUE #264: upgrade karma-runner to 0.12
https://github.com/karma-runner/karma/blob/d5eddf1e69957ec07f88fa9893bf78512f47dc73/CHANGELOG.md#v0120-2014-03-10

### PR DESCRIPTION
**Pull request by lewiscowper**
Fixes #264 I believe. Grunt tests are passing fine anyway.

### CODE REVIEW

**Comment by svnlto** [comment]
Could you update 'all' karma plugins? Just for good measure

**Comment by lewiscowper** [comment]
Yeah, sure. I'll do that asap and try and squash it into one commit for
you. I didn't want to overstep the mark and break something.

**Comment by svnlto** [comment]
that's cool. thanks :thumbsup:

**Comment by lewiscowper** [comment]
That's better, sorry for messing about, I broke my branch.

**Comment by gr2m** [comment]
@tenmilestereo Sorry for let you wait that long. I've manually merged your changes and also updated the respective packages to its latest version again. Cheers!

**Comment by lewiscowper** [comment]
No problem at all, I'm just glad I could help at least some of the way. :) Thanks!

**Pull request closed without merging**
