### PR TITLE
rework project layout

### PR DESCRIPTION
**Pull request by svnlto**

### CODE REVIEW

**Comment by gr2m** [comment]
mind if I remove bower dependencies again, and use npm instead? We currently do that in `dev`

```
// karma.conf.js
{ pattern: 'node_modules/hoodie.js-assets/jquery/jquery.js', watched: false, included: true },
{ pattern: 'node_modules/expect.js/expect.js', watched: false, included: true },
{ pattern: 'node_modules/sinon/pkg/sinon-1.7.3.js', watched: false, included: true },
```

**Comment by svnlto** [comment]
sure, go ahead. must have skipped that accidentally

**Comment by gr2m** [comment]
okay, this is good to go :ship: 

I think next steps are
- stash
- merge
- build
- `grunt bump`

shall we do it together? Merging might be messy, and I suck at git

**Comment by svnlto** [comment]
if things are in sync ( incl. grunt bump ) we might just do a `force push`.

**Comment by gr2m** [comment]
merged via 18809d5

**Pull request closed without merging**
