### PR TITLE
Add name option

### PR DESCRIPTION
**Pull request by aylincakal**
I am not sure but it is just trial.. 
Please let me know about the recent changes

### CODE REVIEW

**Comment by gr2m** [comment]
Hello @aylincakal and welcome to Hoodie :)

I could look in depth into it yet, but when you press on the "Files changed" tab

image

and then on the view button

image

you can [see a preview](https://github.com/aylincakal/hoodie/blob/patch-1/docs/guides/configuration.rst) of how the table will be rendered. Something is still not right yet.

**Comment by gr2m** [comment]
@aylincakal would you like to finish up this PR? Please let me know if you have any questions. And no rush, just let me know when you think you can get back to it. Otherwise I’d like to give someone else the opportunity to have a go at this issue :)

**Comment by aylincakal** [comment]
Hi Gregor! :)

My apologies for my delayed response. I had no time to work on this project and maybe you can give a chance to other people. Sorry for that!

Thank you,
Aylin Çakal

**Comment by gr2m** [comment]
no need to apologise, Aylin. You are always welcome to come back for another issue, please feel free to ping me directly if you have any questions!

**Pull request closed without merging**
