### PR TITLE
removed dispose function and references to dispose throughout

### LINKED ISSUE #227: remove hoodie.dispose()
... until we actually have a need for it

### PR DESCRIPTION
**Pull request by lewiscowper**
Should fix #227. If you just want stuff commented out, then that's fair enough, I can change that, but here it is with dispose() removed.

### CODE REVIEW

**Comment by gr2m** [comment]
Looks good

**Comment by chrisdwheatley** [comment]
:+1:

**Comment by svnlto** [comment]
Looks good tho, just checking with the build to see why it's error'ing again.. Probably down to saucelabs..

**Pull request merged**
